name: Docker Image CI
on:
  push:
    paths:
        - ".devcontainer/Dockerfile"
        - ".github/**"
    branches: [master]
  pull_request:
    paths:
        - ".devcontainer/Dockerfile"
        - ".github/**"
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        ghc: ["9.4.4"]
        stack: ["recommended"]
        resolver: ["default"]
        cabal: ["recommended"]
        hls: ["recommended"]
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./.devcontainer/ --file ./.devcontainer/Dockerfile --build-arg GHC_VERSION=${{ matrix.ghc }} --build-arg STACK_RESOLVER=${{ matrix.resolver }} --build-arg STACK_VERSION=${{ matrix.stack }} --build-arg CABAL_VERSION=${{ matrix.cabal }} --build-arg HLS_VERSION=${{ matrix.hls }} --tag vlza/haskelldevenv:${{ matrix.ghc }}-${{ matrix.resolver }}-${{ matrix.resolver }}-$(date +%s)
